### ISSUE TITLE
Redirection TLD cannot be more than 5 characters

### ISSUE THREAD

**Issue by shprink** [OpenBankingToolkit/openbanking-directory#77]
Context:

![image](https://user-images.githubusercontent.com/1388706/75566132-7cbe8b80-5a4f-11ea-96d9-c1bf4d724d6c.png)

**Comment by BohoCode** [comment]
This regex could be better. IP addresses aren't accepted, and invalid urls such as the following are accepted;
`http://invalid.com/perl.cgi?key= | http://web-site.com/cgi-bin/perl.cgi?key1=value1&key2`

A better regex would be that suggested by this site;
https://www.regextester.com/94502

i.e. `^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$`

**Comment by BohoCode** [comment]
The inital commit #76 fixed zenId 52351

**Comment by BohoCode** [comment]
Opened new issue to deal with enhancement of the regex
